shentufoundation/shentu

cmd/certikcli/main.go, go.mod, go.sum, toolsets/oracle-operator/README.md, toolsets/oracle-operator/contracts/ISecurityPrimitive.sol, toolsets/oracle-operator/contracts/README.md, toolsets/oracle-operator/contracts/SecurityPrimitive.sol, toolsets/oracle-operator/contracts/SecurityPrimitiveOnChain.sol, toolsets/oracle-operator/main.go, toolsets/oracle-operator/oracle-operator.toml, toolsets/oracle-operator/querier/http.go, toolsets/oracle-operator/querier/http_test.go, toolsets/oracle-operator/querier/types/config.go, toolsets/oracle-operator/runner/const.go, toolsets/oracle-operator/runner/listener.go, toolsets/oracle-operator/runner/pusher.go, toolsets/oracle-operator/runner/runner.go, toolsets/oracle-operator/runner/tx.go, toolsets/oracle-operator/runner/types/config.go, toolsets/oracle-operator/runner/types/flags.go, toolsets/oracle-operator/types/config.go, toolsets/oracle-operator/types/config_test.go, toolsets/oracle-operator/types/context.go, toolsets/oracle-operator/types/context_test.go, toolsets/oracle-operator/types/flags.go, toolsets/oracle-operator/types/logger.go, toolsets/oracle-operator/types/logger_test.go, toolsets/oracle-operator/types/msgs.go
Closes: #1 
Added oracle operator and corresponding `certikcli` command. The operator can be run by
```
certikcli oracle-operator [<flags>]
```
Detailed instructions can be found at `toolsets/oracle-operator/README.md`.
______
______
For admin use:
=> oracle: Added toolset oracle-operator

CHANGELOG.md, x/oracle/abci.go, x/oracle/handler.go, x/oracle/internal/keeper/task.go, x/oracle/internal/types/msgs.go, x/oracle/internal/types/task.go
Related: #3 
- Implemented a detailed `aggregate_task` event.
- Added block height field in the task type.
- Added weight and reward fields in the response type.
- Temporarily disable the feature that one can create operator for others.
______
______
For admin use:
=> oracle: Updated events and added useful fields in task types

x/shield/abci.go, x/shield/genesis.go, x/shield/handler.go, x/shield/keeper/collateral.go, x/shield/keeper/invariants.go, x/shield/keeper/keeper.go, x/shield/keeper/pool.go, x/shield/keeper/provider.go, x/shield/keeper/withdraw.go, x/shield/module.go, x/shield/simulation/genesis.go, x/shield/simulation/operations.go, x/shield/types/errors.go, x/shield/types/genesis.go, x/shield/types/types.go
Closes: #XXX
Related: #27
Adds another level of invariants to the existing module coins invariant, along with some renaming refactorings.
______
______
For admin use:
=> Add invariants, support withdraw state export, and fix a bug in handling CertiK collateral

x/shield/handler.go, x/shield/keeper/rewards.go, x/shield/simulation/decoder.go, x/shield/simulation/genesis.go, x/shield/simulation/operations.go, x/shield/types/keys.go, x/shield/types/types.go
Closes: #37 
removes clearpayout tx and pendingpayout store from shield module
______
______
For admin use:
=> shield: remove clearpayouts and relevant stores

.circleci/config.yml, x/shield/abci.go, x/shield/genesis.go, x/shield/keeper/collateral.go, x/shield/keeper/provider.go, x/shield/keeper/withdraw.go, x/shield/simulation/genesis.go, x/shield/simulation/operations.go, x/shield/types/errors.go, x/shield/types/keys.go, x/shield/types/params.go, x/shield/types/types.go
- withdrawal to withdraw everywhere for consistency
- linters added to CI
=> shield: style fixes

x/auth/module.go, x/auth/simulation/genesis.go, x/auth/simulation/operations.go, x/oracle/module.go
Implemented simulation of manual vesting account unlocking for auth module. 
______
______
For admin use:
=> auth: add custom simulation package

client/lcd/swagger-ui/swagger.yaml, x/shield/client/cli/tx.go, x/shield/client/rest/query.go, x/shield/keeper/purchase.go, x/shield/types/types.go
Closes: #48 #49 
* Fixed API for creating a pool.
* Added query methods for a purchase and a provider.
* Fixed display of txhash in query results.
______
______
For admin use:
=> shield: Updated RESTful APIs

common/appbasic.go, x/cert/client/rest/query.go, x/cert/client/rest/rest.go, x/cert/client/rest/tx.go, x/cert/internal/types/querier.go, x/cvm/client/rest/query.go, x/cvm/client/rest/rest.go, x/cvm/client/rest/tx.go, x/cvm/internal/types/querier.go, x/gov/client/rest/query.go, x/oracle/client/rest/query.go, x/oracle/client/rest/rest.go, x/oracle/client/rest/tx.go, x/oracle/internal/types/querier.go, x/shield/client/rest/query.go, x/shield/client/rest/rest.go, x/shield/keeper/querier.go, x/shield/types/querier.go
Closes: #XXX
Related: #XXX
Refactor REST clients in `x/cert`, `x/cvm`, `x/gov` & `x/shied` for better code uniformity. This shall be an ongoing process for the foreseeable future.
______
______
For admin use:
=> [refactor] REST client in Cert, CVM, Gov & Shield

x/shield/alias.go, x/shield/keeper/proposal.go, x/shield/keeper/purchase.go
Closes: #XXX
Related: #XXX
Trying to fix the import/export issue in simulations
______
______
For admin use:
=> shield: Removed empty time slice for purchase queue

x/shield/keeper/proposal.go
Closes: #XXX
Related: #XXX
Fixed a bug when locking collaterals.
______
______
For admin use:
=> shield: Fixed a bug when locking collaterals

x/shield/abci.go
Closes: #XXX
Related: #XXX
______
______
For admin use:
=> shield: fix premium distribution rounding error

toolsets/oracle-operator/contracts/SecurityPrimitiveOnChain.sol
Update SecurityPrimitiveOnChain contract for new score range.
=> refactor(oracle): Update score range in SecurityPrimitiveOnChain Contract

app/app.go, x/gov/test_common.go, x/shield/keeper/keeper.go, x/shield/keeper/pool.go, x/shield/keeper/purchase.go, x/shield/simulation/operations.go, x/shield/types/errors.go, x/shield/types/expected_keepers.go
Closes: #XXX
Related: #XXX
______
______
For admin use:
=> shield: claim period adjustment

app/app.go, x/gov/simulation/operations.go, x/gov/test_common.go, x/shield/abci.go, x/shield/genesis.go, x/shield/keeper/collateral.go, x/shield/keeper/invariants.go, x/shield/keeper/keeper.go, x/shield/keeper/pool.go, x/shield/keeper/proposal.go, x/shield/keeper/purchase.go, x/shield/keeper/querier.go, x/shield/keeper/test_common.go, x/shield/keeper/withdraw.go, x/shield/simulation/operations.go, x/shield/types/errors.go, x/shield/types/expected_keepers.go
Closes: #XXX
Related: #XXX
Pools are closed without all states correctly updated. Fixed closing pools and enabled simulations for claim proposals.
______
______
For admin use:
=> shield: fix closing pools

x/oracle/internal/keeper/task.go, x/oracle/internal/types/params.go
Closes: #62 
The security score was ranged from 0 to 255, which is not intuitive. Changed security score range to [0, 100] now.
______
______
For admin use:
=> oracle: change security score range from [0, 255] to [0, 100]

x/oracle/handler.go, x/oracle/internal/keeper/operator.go, x/oracle/internal/types/events.go, x/oracle/internal/types/msgs.go
Closes: #XXX
Related: #XXX
There are some missing events in the oracle module. The following events are added in this update:
- `create_operator`
- `remove_operator`
- `add_collateral`
- `reduce_collateral`
Other updates:
- A new attribute `reward` in event `withdraw_reward`.
- Attribute `address` in `withdraw_reward` is changed to `operator`.
______
______
For admin use:
=> oracle: modify events

x/shield/keeper/pool.go, x/shield/types/msg.go
Closes: #XXX
Related: #XXX
We required additional time to be not less than minimum pool life. It doesn't seem to be necessary. Removed the check in this update.
______
______
For admin use:
=> shield: remove unnecessary additional time check when updating pools

x/shield/client/cli/tx.go, x/shield/keeper/invariants.go, x/shield/keeper/proposal.go
Closes: #XXX
Related: #XXX
There are several bug found in the implementation of shield reimbursement. They are fixed and tested now.
______
______
For admin use:
=> shield: fix bugs related to reimbursement

x/shield/keeper/purchase.go, x/shield/types/codec.go, x/shield/types/keys.go, x/shield/types/types.go
Closes: #XXX
Related: #XXX
______
______
For admin use:
=> shield: refactor types

x/shield/abci.go, x/shield/genesis.go, x/shield/handler.go, x/shield/keeper/collateral.go, x/shield/keeper/invariants.go, x/shield/keeper/keeper.go, x/shield/keeper/pool.go, x/shield/keeper/proposal.go, x/shield/keeper/provider.go, x/shield/keeper/purchase.go, x/shield/keeper/querier.go, x/shield/keeper/withdraw.go, x/shield/types/expected_keepers.go, x/shield/types/genesis.go, x/shield/types/mixed_coins.go, x/shield/types/msg.go, x/shield/types/proposal.go, x/shield/types/types.go
Closes: #XXX
Related: #XXX
- The `ExpirationTime` field of purchases does not function as its name. Renamed it to `DeleteTime`
- Modified comments in the shield module to follow a good comment style.
______
______
For admin use:
=> shield: update variable names and comments

x/shield/genesis.go, x/shield/keeper/collateral.go, x/shield/keeper/params.go, x/shield/keeper/pool.go, x/shield/keeper/provider.go, x/shield/keeper/purchase.go, x/shield/keeper/withdraw.go, x/shield/simulation/genesis.go, x/shield/simulation/operations.go, x/shield/types/errors.go, x/shield/types/genesis.go, x/shield/types/keys.go, x/shield/types/params.go, x/shield/types/types.go
Closes: #XXX
Related: #XXX
______
______
For admin use:
=> shield: update logics and simulations

x/bank/client/cli/tx.go, x/bank/client/rest/tx.go, x/bank/handler.go, x/bank/internal/types/msgs.go
Closes: #76
Related: #XXX
______
______
For admin use:
=> enable new manual vesting accounts post-genesis

app/app.go, x/bank/alias.go, x/bank/cosmos_alias.go, x/bank/handler.go, x/bank/internal/types/events.go, x/bank/internal/types/msgs.go, x/bank/module.go, x/bank/simulation/operations.go, x/cvm/internal/keeper/test_helpers.go
Closes: #XXX
Related: #XXX
______
______
For admin use:
=> bank: fix lockedsend bug, re-route send through custom bank module

x/shield/client/cli/tx.go, x/shield/handler.go, x/shield/keeper/collateral.go, x/shield/keeper/pool.go, x/shield/keeper/provider.go, x/shield/keeper/purchase.go, x/shield/keeper/rewards.go, x/shield/simulation/operations.go, x/shield/types/msg.go, x/shield/types/types.go
Closes: #XXX
Related: #XXX
- Added pool limit for each pool.
- Fixed a bug for purchasing shield.
- Disabled foreign token related transactions.
- Code refinements.
______
______
For admin use:
=> shield: add shield limit for pools and make code refinements

x/oracle/simulation/genesis.go, x/oracle/simulation/operations.go
Create-task tx will be oriented and all other txs will be triggered at certain heights as future operations. 
______
______
For admin use:
=> oracle: add task-related simulations

x/shield/abci.go, x/shield/client/cli/tx.go, x/shield/keeper/pool.go, x/shield/simulation/operations.go, x/shield/types/msg.go
Added supports for pool closures. Pools will be closed when there is no shield in the pool and the shield limit is set to negative.
______
______
For admin use:
=> shield: close pools based on shield and shield limit

x/shield/abci.go, x/shield/genesis.go, x/shield/keeper/pool.go, x/shield/keeper/purchase.go, x/shield/keeper/rewards.go, x/shield/types/genesis.go, x/shield/types/keys.go, x/shield/types/mixed_coins.go, x/shield/types/types.go
Closes: #96 
Changed the ways of distributing services fees so that they are distributed throughout protection periods.
______
______
For admin use:
=> shield: distribute shield service fees throughout protection periods

x/gov/client/rest/query.go, x/shield/client/cli/query.go, x/shield/client/rest/query.go, x/shield/keeper/provider.go, x/shield/keeper/purchase.go, x/shield/keeper/querier.go, x/shield/types/querier.go
=> Revert "shield: add query providers and purchases (#106)"

x/oracle/simulation/operations.go, x/shield/client/cli/query.go, x/shield/client/rest/query.go, x/shield/client/rest/tx.go, x/shield/genesis.go, x/shield/keeper/keeper.go, x/shield/keeper/params.go, x/shield/keeper/pool.go, x/shield/keeper/purchase.go, x/shield/keeper/querier.go, x/shield/simulation/decoder.go, x/shield/types/genesis.go, x/shield/types/keys.go, x/shield/types/querier.go
Closes: #XXX
Related: #XXX
- Added a query endpoint for global state.
- Updated APIs.
- Fixed a bug in distributing service fees.
______
______
For admin use:
=> shield: update APIs and fix bugs

x/shield/handler.go, x/shield/keeper/purchase.go, x/shield/simulation/genesis.go, x/shield/types/errors.go, x/shield/types/params.go
Closes: #XXX
Related: #XXX
Add a requirement on minimum amount for shield purchases. It is set to 50CTK by default.
______
______
For admin use:
=> shield: add a requirement on minimum amount for shield purchases

x/shield/keeper/invariants.go, x/shield/keeper/rewards.go
Closes: #XXX
Related: #110 
______
______
For admin use:
=> shield: fix remaining service fees tracking & add module account invariant

.golangci.yml, x/cert/internal/types/certificate.go
Closes: #XXX
Related: #XXX
Add a new certificate type for identity.
Example:
```
certikcli tx cert issue-certificate identity general certikpub1addwnpepq07qjj628mrxr995sqjzdwhuf08pdgvyudmskp3wd9atv6gnu47kz9cf2xj --from node0 --fees 5000uctk -y -b block
```
Result:
```
- certificateid: 059dee43c3d0ddc26c456385d200661e4c61593028bc4005a44944511e00
certificatetype: Identity
requestcontent:
requestcontenttype: 4
requestcontenttypename: General
requestcontent: certikpub1addwnpepq07qjj628mrxr995sqjzdwhuf08pdgvyudmskp3wd9atv6gnu47kz9cf2xj
certificatecontent: []
description: ""
certifier: certik1k40lxj02080w6l9hsgmx8ns3p6ncauef9qe8ju
txhash: 9001b7cbdc7ef30c69351da5c695dcd3b7e114d1322154bccb2bc2a853dd4ec6
```
______
______
For admin use:
=> cert: add a new certificate type for identity

x/cert/client/cli/query.go
Closes: #XXX
Related: #XXX
Fixed query endpoint for certificate by ID. Interfaces can not be decoded before they are registered.
______
______
For admin use:
=> cert: fix query endpoint for certificate by ID

x/distribution/module.go, x/mint/genesis.go, x/shield/types/params.go, x/slashing/module.go, x/staking/module.go
Closes: #XXX
Related: #XXX
______
______
For admin use:
=> sdk: adjust genesis params

x/bank/handler.go, x/bank/internal/types/events.go
Closes: #123 
Fixed incorrect locked send event and made it a new event in order not to bring confusions after chain upgrade.
______
______
For admin use:
=> bank: fix incorrect locked send event

x/auth/handler.go
Closes: #125 
Related: #XXX
______
______
For admin use:
=> auth: update delegated_vesting and delegated_free when unlocking

cmd/certikcli/main.go, x/cvm/client/cli/query.go, x/cvm/client/rest/query.go, x/cvm/client/utils/errors.go, x/cvm/client/utils/query.go, x/cvm/internal/keeper/querier.go, x/cvm/internal/keeper/querier_test.go, x/cvm/internal/types/cvm_account.go, x/cvm/internal/types/querier.go
Closes: #XXX
Related: #119
Testing
- cli
query account address
```
certikcli query account certik1ra6ljqtkv3ph7rtkx79q6thv7cpjx80ecwwpp5
|
address: certik1ra6ljqtkv3ph7rtkx79q6thv7cpjx80ecwwpp5
coins:
- denom: uctk
amount: "99925000"
public_key: certikpub1addwnpepqf0zmt5ympar4fpvdvy4znxqvqyjw8pkehg9fcmm8kpa0vyu7gd2z9qewv9
account_number: 0
sequence: 6
```
query contract address
```
certikcli query account certik1sxhl8qg8mksxxhayekcn3t2apw6r0aup5hdhdt
|
address: certik1sxhl8qg8mksxxhayekcn3t2apw6r0aup5hdhdt
coins:
- denom: uctk
amount: "0"
public_key: ""
account_number: 13
sequence: 0
code: 6080604052348015600F57600080FD5B506004361060325760003560E01C806360FE47B11460375780636D4CE63C146062575B600080FD5B606060048036036020811015604B57600080FD5B8101908080359060200190929190505050607E565B005B60686 …
```
=> cvm: Improve account query to include CVM related info

log.txt, x/gov/simulation/operations.go
**targeting at branch of #95**
* Increased the number of voters in both certifier and validator voting round. 
* increased the chance of yes votes in validator voting round. 
______
______
For admin use:
=> gov: increase voters and yes votes in simulation

x/mint/internal/keeper/keeper.go, x/mint/internal/types/expected_keepers.go, x/shield/genesis.go, x/shield/keeper/invariants.go, x/shield/keeper/purchase.go, x/shield/keeper/querier.go, x/shield/keeper/staking_purchase.go, x/shield/simulation/operations.go
Closes: #XXX
Related: #XXX
fixes some issues related to staking for shield auto renewal.
______
______
For admin use:
=> fix staking for shield renewals

x/shield/client/cli/query.go, x/shield/client/rest/query.go, x/shield/keeper/proposal.go, x/shield/keeper/querier.go, x/shield/types/errors.go, x/shield/types/querier.go
Related: #120 
Implemented query endpoints for reimbursements in the shield module.
______
______
For admin use:
=> shield: add query endpoints for reimbursements

x/auth/handler.go
Closes: #XXX
Related: #XXX
______
______
For admin use:
=> auth: add update check for delegated vesting and free update for unlock

x/shield/genesis.go, x/shield/keeper/pool.go, x/shield/keeper/purchase.go
Closes: #XXX
Related: #XXX
______
______
For admin use:
=> shield: remove height check in endblocker purchase expiration processing

x/auth/handler.go, x/gov/handler.go, x/shield/alias.go, x/shield/handler.go, x/shield/keeper/collateral.go, x/shield/keeper/purchase.go, x/shield/simulation/operations.go
Closes: #151 
Related: #XXX
Disabled operations added after v1.0.0 before upgrade height.
______
______
For admin use:
=> Disable newly added operations before upgrade height

common/assets.go, x/shield/keeper/proposal.go
Closes: #162
Related: #XXX
______
______
For admin use:
=> fix unlocking in claim proposal route

x/cert/internal/keeper/certificate.go, x/cert/internal/keeper/test_common.go, x/cert/internal/types/expected_keepers.go, x/cert/simulation/operations.go, x/gov/internal/keeper/proposal.go, x/gov/internal/keeper/tally.go, x/gov/internal/keeper/vote.go, x/gov/internal/types/expected_keeper.go, x/gov/simulation/operations.go, x/shield/keeper/proposal.go
Closes: #155 
Related: #XXX
Only allow certified identities to vote for shield claim proposals.
______
______
For admin use:
=> shield: require voters for shield claim proposals to be certified identities

CHANGELOG.md, x/cert/client/rest/query.go, x/gov/client/rest/query.go, x/shield/client/rest/query.go, x/staking/client/rest/query.go
=> rest: Set default query limit to 100

CHANGELOG.md, x/shield/keeper/proposal.go
Closes: #172 
Related: #XXX
______
______
For admin use:
=> shield: fix indexing error from payout from unbonding delegations

CHANGELOG.md, x/cert/client/cli/tx.go, x/cert/client/rest/rest.go, x/cert/client/rest/tx.go, x/cert/genesis.go, x/cert/handler.go, x/cert/internal/keeper/certificate.go, x/cert/internal/keeper/querier_certificate.go, x/cert/internal/types/certificate.go, x/cert/internal/types/errors.go, x/cert/internal/types/genesis.go, x/cert/internal/types/keys.go, x/cert/internal/types/msgs.go, x/cert/keeper_test.go, x/cert/simulation/decoder.go, x/cert/simulation/operations.go
Reverts certikfoundation/shentu#179 to exclude it from the upcoming release.
To be merged in for a later update.
=> Revert "cert: Refactor store keys"

app/app.go, simapp/simapp.go
Closes: #XXX
Related: #169 
______
______
For admin use:
=> SDK: add in IBC

common/assets.go, x/shield/keeper/purchase.go
Closes: #215 
Fixed incorrect service fees distribution.
______
______
For admin use:
=> Fixed incorrect service fees distribution

app/app.go, simapp/simapp.go, x/cert/simulation/decoder_test.go, x/cvm/simulation/decoder_test.go, x/gov/endblocker.go, x/gov/keeper/msg_server.go, x/gov/simulation/decoder_test.go, x/gov/simulation/operations.go, x/shield/types/codec.go
Closes: #XXX
Related: #169
______
______
For admin use:
=> shield: fix shield claim proposal router handling

app/app.go, x/shield/keeper/invariants.go
Closes: #228 
Related: #XXX
______
______
For admin use:
=> Invariant optimization & removal

Makefile
Enable ledger support in build env.
______
______
For admin use:
=> Enable Ledger Support in Binary

simapp/test_helpers.go
Closes: #XXX
Related: #XXX
______
______
For admin use:
=> CVM: Fix cvm test

app/app.go, app/app_test.go
Closes: #XXX
Related: #XXX
______
______
For admin use:
=> APP: fix module account coin receiving

common/assets.go, x/auth/keeper/msg_server.go, x/shield/abci.go
Closes: #XXX
Related: #XXX
______
______
For admin use:
=> APP: remove upgrade heights reference

go.mod, go.sum
Upgrade Cosmos SDK to 0.42.3 from 0.41.0
=> SDK: Upgrade to 0.42.3

go.sum, proto/shentu/shield/v1alpha1/query.proto, x/shield/client/cli/query.go, x/shield/keeper/grpc_query.go, x/shield/types/query.pb.go, x/shield/types/query.pb.gw.go
updates confusing shield endpoints for better readability and precise functionality.
______
______
For admin use:
=> shield: update shield grpc query endpoints

app/app.go
Closes: #270 
Related: #XXX
______
______
For admin use:
=> enable gRPC for /cosmos/base/tendermint/v1beta/*

x/shield/keeper/msg_server.go
Closes: #285 
Related: #XXX
______
______
For admin use:
=> shield: fix emitted events for some of the tx routes

.codecov.yml, README.md
Closes: #XXX
Related: #XXX
______
______
For admin use:
=> CI: Fix Codecov

app/app.go, app/export.go, app/sim_test.go, simapp/simapp.go
Closes: #287 
Related: #XXX
______
______
For admin use:
=> APP: Remove Crisis from CertiKApp & Route Simulation Tests Through SimApp

x/cert/simulation/proposals.go
Closes: #XXX
Related: #XXX
______
______
For admin use:
=> cert: Fix `cert` simulations

x/oracle/keeper/keeper_test.go
=> test: fix oracle test

simapp/simapp.go, x/nft/keeper/grpc_query_test.go, x/nft/keeper/keeper_test.go, x/nft/types/keys.go, x/nft/types/msgs_test.go
Closes: #XXX
Related: #281, #284 
Unit testing for the NFT module.
______
______
For admin use:
=> NFT: add unit testing

go.mod, x/oracle/genesis_test.go, x/oracle/keeper/keeper_test.go, x/oracle/keeper/operator.go, x/oracle/keeper/withdraw_test.go, x/oracle/types/keys_test.go, x/oracle/types/msgs_test.go, x/oracle/types/params_test.go, x/oracle/types/withdraw_test.go
Closes: #XXX
Related: #XXX
______
______
For admin use:
=> Oracle Test files

Dockerfile
This PR attempts to optimize the size of shentu's docker image leveraging multi-stage builds, layer/dependency minimization and various other techniques. As a result, the final image is now ~77MB, a 95% reduction from 1.67GB.
______
______
For admin use:
=> Chore: Docker Image Size Optimization

CHANGELOG.md
Closes: #XXX
Related: #XXX
______
______
For admin use:
=> add missed change logs

x/shield/keeper/grpc_query_test.go, x/shield/keeper/helpers_test.go, x/shield/keeper/provider_test.go
Closes: #XXX
Related: #XXX
______
______
For admin use:
=> shield: add test cases

Dockerfile, x/cvm/module.go, x/cvm/types/genesis.go
=> fix: implement cvm validate genesis

Makefile, app/certik/cmd/migrate/migrate.go
Closes: #XXX
Related: #XXX
______
______
For admin use:
=> App: add slashing params modification in migrate funciton

.circleci/config.yml, Makefile
Closes: #XXX
Related: #XXX
Fixes a failing CI lint workflow.
______
______
For admin use:
=> CI: fix lint failure

app/upgrade_handler.go
Closes: #XXX
Related: #XXX
Fix the order of migrations so as to not disturb any other modules during the migrations and have the correct final VM after the migrations.
=> SDK: Fix Migration Order

.circleci/config.yml
Closes: #XXX
Related: #XXX
Re-enable nondeterminism test in favor of #350 to clear out the commit log issues.
=> SIM: Re-enable nondeterminism simulation test

app/app.go
=> Oracle: Fix cert expected keeper error

CHANGELOG.md
Closes: #XXX
Related: #XXX
______
______
For admin use:
=> APP: V2.3.0-rc1

.circleci/config.yml
Closes: #XXX
Related: #XXX
______
______
For admin use:
=> CI: update circleci repo url & go version

.circleci/config.yml
Closes: #XXX
Related: #XXX
______
______
For admin use:
=> CI: fix url capitalization for docker-tagged

x/cvm/keeper/grpc_query.go, x/gov/client/cli/query.go
@AmanRaj1608 identified an issue where a query of a specific deposit was not working. This PR fixes it.
=> Gov: Deposit query fix

x/gov/keeper/tally.go
Closes: #XXX
Related: #XXX
______
______
For admin use:
****
=> Gov: fix security tally

x/shield/client/cli/query.go
@fuzious identified two shield query commands that have incorrect logic.
=> Shield: Fix query commands

x/shield/client/cli/tx.go
Closes: #XXX
Related: #XXX
______
______
For admin use:
=> Shield: Removed  unused variable

CHANGELOG.md, app/app.go, app/forks.go, app/mva/constants.go, app/mva/fork_test.go, app/mva/forks.go, x/staking/teststaking/helper.go
Closes: #XXX
Related: #XXX
______
______
For admin use:
=> AUTH: add MVA delegation amounts fix

devtools/Makefile
Closes: #377 
Related: #XXX
This pr is to solve to problem in issue#377. The tendermintdev/sdk-proto-gen version is set to v0.3. This allows code to be auto-generated from the proto files.
______
______
For admin use:
=> Shield: set tendermintdev/sdk-proto-gen docker image version to v0.3

app/app.go
Closes: #XXX
Related: #XXX
______
______
For admin use:
=> GOV: add in missing ibc proposal handlers

go.mod
Closes: #XXX
Related: #XXX
______
______
For admin use:
=> Go: Upgrade go version to 1.18

CHANGELOG.md
Closes: #XXX
Related: #XXX
Updates the changelog so it reflects recent changes
______
______
For admin use:
=> correct changelog for SDK upgrade

CHANGELOG.md, x/shield/keeper/collateral.go
Closes: #XXX
Related: #XXX
______
______
For admin use:
=> shield: add withdraw rewards after deposit/withdraw collateral execution route

app/app.go, app/sim_test.go
Closes: #449 
Related: #XXX
______
______
For admin use:
=> App: add setmoduleversionamp in initchainer

x/shield/simulation/params.go
Closes: #XXX
Related: #XXX
______
______
For admin use:
=> Fix the Error when running golangci-lint.

Dockerfile, devtools/localnet/localnet_client_setup.sh, tests/e2e/e2e_setup_test.go, tests/e2e/e2e_util_test.go
Closes: #XXX
Related: #XXX
______
______
For admin use:
=> TEST: fix e2e test

devtools/relayer_scripts/README.md, devtools/relayer_scripts/relayer.sh, devtools/relayer_scripts/setup_chains.sh
Closes: #XXX
Related: #XXX
______
______
For admin use:
=> App:change name from certik to shentud

CHANGELOG.md
Closes: #XXX
Related: #XXX
______
______
For admin use:
=> update changelog for v2.6.0

x/auth/simulation/genesis.go, x/auth/simulation/operations.go, x/bank/simulation/operations.go, x/cert/simulation/operations.go, x/cvm/simulation/sim_utils.go, x/cvm/simulation/sim_utils_test.go, x/gov/simulation/operations.go, x/oracle/simulation/operations.go, x/staking/simulation/operations.go
This PR is the 2nd part of the effort to solve [this issue](https://github.com/ShentuChain/shentu/issues/504).
=> fix the simulation failure caused the introduction of Cosmos SDK v0.45.9

.github/workflows/dependabot.yml
Closes: #XXX
Related: #XXX
______
______
For admin use:
=> CI: Fix Dependabot Automerge

app/app.go, x/bounty/handler_test.go, x/bounty/module_test.go, x/bounty/types/genesis.go, x/bounty/types/genesis_test.go, x/bounty/types/msg_test.go
1. Add test case.
2. Add bounty account.
3. set default value.
Closes: #XXX
Related: #XXX
______
______
For admin use:
=> Add bounty module account

x/bounty/client/cli/helper.go
Closes: #XXX
Related: #XXX
______
______
For admin use:
=> Bounty cli help information

app/upgrade_handler.go
Closes: #XXX
Related: #XXX
______
______
For admin use:
=> Add bounty upgrade

x/bounty/keeper/finding.go, x/bounty/types/msgs.go
Closes: #XXX
Related: #XXX
______
______
For admin use:
=> Bounty program validate

x/bounty/client/cli/tx.go
Closes: #XXX
Related: #XXX
______
______
For admin use:
=> Bounty: fix cli cancel bug

x/bounty/client/cli/helper.go, x/bounty/client/cli/tx.go, x/bounty/client/cli/utils_test.go
Closes: #XXX
Related: #XXX
______
______
For admin use:
=> Bounty any parse

x/bounty/client/cli/tx.go, x/bounty/client/cli/utils.go, x/bounty/client/cli/utils_test.go, x/bounty/keeper/finding.go, x/bounty/keeper/finding_test.go, x/bounty/keeper/msg_server.go, x/bounty/keeper/msg_server_test.go, x/bounty/types/bounty.go, x/bounty/types/errors.go
Closes: #XXX
Related: #XXX
______
______
For admin use:
=> add publickey verification

proto/shentu/oracle/v1alpha1/query.proto, x/oracle/client/cli/query.go, x/oracle/keeper/grpc_query.go, x/oracle/keeper/grpc_query_test.go, x/oracle/types/keys.go, x/oracle/types/query.pb.go, x/oracle/types/query.pb.gw.go
Closes: #XXX
Related: #XXX
______
______
For admin use:
=> txTask, txTaskResponse query

app/sim_test.go, x/oracle/simulation/genesis.go, x/oracle/simulation/operations.go
Closes: #XXX
Related: #XXX
______
______
For admin use:
=> Simulaton for createTxTask

tests/e2e/e2e_oracle.go, tests/e2e/e2e_setup_test.go, tests/e2e/e2e_test.go, tests/e2e/e2e_util_test.go
Closes: #XXX
Related: #XXX
______
______
For admin use:
=> precog e2e test case

x/oracle/abci.go, x/oracle/keeper/task.go, x/oracle/keeper/task_test.go
Closes: #XXX
Related: #XXX
______
______
For admin use:
=> add refund bounty

x/oracle/keeper/msg_server_test.go, x/oracle/keeper/task_test.go, x/oracle/types/genesis.go, x/oracle/types/msgs.go
Closes: #XXX
Related: #XXX
______
______
For admin use:
=> add some edge-test

tests/e2e/e2e_test.go, x/oracle/abci.go, x/oracle/client/cli/tx.go, x/oracle/keeper/grpc_query_test.go, x/oracle/keeper/msg_server.go, x/oracle/types/keys.go
Closes: #XXX
Related: #XXX
______
______
For admin use:
=> change base64 to hex

CHANGELOG.md
Closes: #XXX
Related: #XXX
______
______
For admin use:
=> Changelog 2.7.0

go.mod, go.sum
Closes: #XXX
Related: #XXX
______
______
For admin use:
=> ics23 use v0.8.0

go.mod, go.sum
Closes: #XXX
Related: #XXX
______
______
For admin use:
=> Upgrade IBC to v4.2.1

go.mod, go.sum
Closes: #XXX
Related: #XXX
______
______
For admin use:
=> Upgrade ics23 to v0.9.0

x/cert/legacy/v2/store.go
Closes: #XXX
Related: #XXX
______
______
For admin use:
=> skip empty certificate's proposer

app/upgrade_handler.go, app/upgrade_handler_test.go
the following two specific proposal contents are handled:
ShieldClaimProposal
CertifierUpdateProposal
=> add address prefix conversion for specific gov proposal content

CHANGELOG.md
=> add v2.7.2 in Changelog

app/app.go, app/upgrade_handler.go
Closes: #XXX
Related: #XXX
______
______
For admin use:
=> add group module

x/shield/keeper/keeper.go
Closes: #XXX
Related: #XXX
______
______
For admin use:
=> fix audit: GetPoolsBySponsor should use sponsor

go.mod, go.sum
fix bug for client sign-mode
Closes: #XXX
Related: #XXX
______
______
For admin use:
=> update: cosmossdk.io/client/v2 v2.0.0-beta.3

x/bounty/keeper/migrations.go, x/bounty/migrations/v3/store.go
Closes: #XXX
Related: #XXX
______
______
For admin use:
=> Fix Bounty Migration

x/bounty/types/params.go
Closes: #XXX
Related: #XXX
______
______
For admin use:
=> update(bounty): checkerRate set 0
